### PR TITLE
Migrate from .net 4.0 to netstandard2.0 so it can be used it in .net core-based projects

### PR DESCRIPTION
**Pull request by stevebering**
We are working to migrate our project from .net 4.6 to .net 6.0 and would like to continue to use DapperParameters to provide testable data access code. However, since the current nuget package does not support .net standard, we are not able to use it. This PR migrates the dependencies from .net 4 based dependencies to .net standard 2.0 based dependencies. This requires an upgrade to the Dapper dependency to a minimum of 1.50, since that is when they supported .net standard. I also upgraded the test and example projects to .net 4.6.2 because that was necessary to support .net standard 2.0.

### CODE REVIEW

**Comment by richinator38** [comment]
Nice job! Thanks!

**Comment by stevebering** [comment]
Is there additional work that I can help with to get a new version of the nuget package released? I was thinking that we would want to make it a new major version since it will break users who are using it in .net4, which the previous version supported. Thank you.

**Comment by richinator38** [comment]
I'll get er done tonight. Thanks for offering to do it.

**Comment by richinator38** [comment]
Looks like it won't let me update the existing one since my login was changed (I think that's the reason). So I created a new one called DapperParametersStandard. It is currently processing but should be available soon.

**Pull request merged**
